### ISSUE TITLE
Add writeups for prompt.ml levels -2 to -4

### ISSUE THREAD

**Issue by gsingh93** [cure53/XSSChallengeWiki#7] opened 2015-10-12 19:40 UTC
There were some new levels added to prompt.ml, writeups need to be added for them.

**Comment by cure53** [comment] 2015-10-14 14:14
I am not sure if the author is ready for the solutions to be public.

@filedescriptor What do you think?

**Comment by filedescriptor** [comment] 2015-10-14 14:37
I am totally okay with that.

**Comment by cure53** [comment] 2015-10-14 14:49
@filedescriptor Cool :)

@gsingh93 Pull requests are welcome!

**Comment by cure53** [comment] 2016-04-02 13:16
@filedescriptor As far as I know, this has been fixed in Chromium for some months by now. Should we document the solution from back then?

**Comment by filedescriptor** [comment] 2016-04-02 13:25
No objection!

**Comment by cure53** [comment] 2016-04-02 13:44
IIRC it was `)},prompt(1)}{{//` correct?

**Comment by filedescriptor** [comment] 2016-04-02 13:48
`)},{0:prompt(1` worked. But I'm not sure if yours worked as well.

**Comment by cure53** [comment] 2016-04-02 13:50
Mine worked in a local set-up on Chrome 25. Not sure, what Chrome version it worked in last - and the vectors changed over time due to different `with` blocks in the browser code.

**Comment by filedescriptor** [comment] 2016-04-02 13:57
I think we can mention either one - because we focus more on the peculiar instead of the actual implementation.

**Comment by cure53** [comment] 2016-04-02 15:02
Here is a draft version for sanity check:

https://github.com/cure53/XSSChallengeWiki/wiki/prompt.ml#hidden-level--4

**Comment by filedescriptor** [comment] 2016-04-02 15:13
lgtm!

**Comment by cure53** [comment] 2016-04-02 15:17
Should we add -2 and -3 as well?

**Comment by filedescriptor** [comment] 2016-04-02 15:20
Sure

**Comment by cure53** [comment] 2016-04-02 15:23
Do you still have the solutions at hand? :) Then I can take care.

**Comment by filedescriptor** [comment] 2016-04-02 15:26
-2: `@if(0)@end` (@cc_on is not necessary)
-3: semi-colon instead of ampersand

**Comment by cure53** [comment] 2016-04-02 15:32
I know - I recall what the way of solving it was, but I didn't wanna spent time on both re-finding the exact solution **and** doing the write-up - thus asking for the solutions in case you still have them - not just the general way :) 

Also not in a hurry here, if you still have the string I'll use it, if not, I'll re-solve :P

**Comment by filedescriptor** [comment] 2016-04-02 15:41
Ah sorry about that. I don't have the original solutions but I've just tried to recall them:
-2: `"><script>@if(0)#@end;prompt(1)@if(0)#@end</script>`
For -3, I am not sure if the API has changed but I can't seem to reproduce anymore

**Comment by cure53** [comment] 2016-04-02 15:42
Thanks :D And same here for "-3", just tried as well.

**Comment by cure53** [comment] 2016-04-02 17:16
I think it was `;callback=prompt(1,` - possible?

**Comment by filedescriptor** [comment] 2016-04-02 18:04
I think it should be something like `"onclick=prompt(1) id="a";callback=a.click;`
because the callback name is validated. We first create a click event handler, and set the callback to reference to its click function to invoke the payload.

**Comment by cure53** [comment] 2016-04-02 18:12
Ah, fair enough. I will use that. Thx :)

**Comment by filedescriptor** [comment] 2016-04-02 18:17
Let me know if you need helps :) By the way I think you can also mention that -3 is a scenario for SOME

**Comment by cure53** [comment] 2016-04-02 18:32
Technically not SOME but COME and that sounds very non-beneficial...

**Comment by cure53** [comment] 2016-04-02 18:40
Ready for a sanity check!

**Comment by filedescriptor** [comment] 2016-04-02 18:47
Looks perfect! Finally the write-up is complete, thanks mario :D

**Comment by cure53** [comment] 2016-04-02 18:59
Thank you :)

**Closed as completed by cure53** 2016-04-02 18:59 UTC
